# Use the official Ubuntu base image (choose your preferred version)
FROM ubuntu:20.04  

RUN apt-get update && apt-get upgrade -y && apt-get install curl -y

RUN apt-get install -y python3 python3-pip
# RUN apt-get install -y python3 python3-pip

WORKDIR /app

COPY . /app

CMD ["python3", "app.py"]
